version: "3"
services:
  hux:
    image: movieproject.jar
    ports:
      - "8080:8080"
    networks:
      - movieshow
    depends_on:
      - mysqlnetflixnew
 
  mysqlnetflixnew:
    image: mysql:latest
    networks:
      - movieshow
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hux  

networks:
  movieshow: